[build]
  publish = "public"

[[redirects]]
  from = "/vacatures/"
  to = "https://career.elgentos.nl"

[[redirects]]
  from = "/tablerates" 
  to = "https://www.tableratesgenerator.com/"

[[redirects]]
  from = "/vacatures/laravel-php-developer/"
  to = " https://career.elgentos.nl/o/laravel-php-developer"

[[redirects]]
  from = "/vacatures/magento-php-backend-developer/"
  to = "https://career.elgentos.nl/o/magento-2-backend-developer"

[[redirects]]
  from = "/vacatures/magento-frontend-developer/"
  to = "https://career.elgentos.nl/o/magento-2-frontend-developer"
